Repository cloud-native-toolkit/terraform-tools-argocd-bootstrap, pull requests merged in 2022-04, with the labels that each got.

#17 Updates openshift-cicd submodule to v1.7.12
  main.tf
Labels: patch, chore

#19 Updates openshift-cicd module to v1.7.13
  main.tf
  test/stages/stage1-resource-group.tf
Labels: bug, patch

#24 Updates openshift-cicd submodule to v1.7.15
  .github/workflows/verify-pr.yaml
  .github/workflows/verify.yaml
  main.tf
Labels: bug, patch

#28 fixes https://github.com/cloud-native-toolkit/terraform-tools-argocd-…
  main.tf
Labels: chore

#31 Fixes openshift-gitops install issue
  main.tf
Labels: bug, patch

#32 Fixes tekton deployment issue
  .github/workflows/update-dependencies.yaml
  main.tf
Labels: bug, patch

#33 Updates openshift-cicd module to v1.8.0
  .github/scripts/update-modules.sh
  main.tf
Labels: enhancement, minor
