Repository cloud-native-toolkit/terraform-tools-argocd-bootstrap, pull requests merged in 2023-07, with the labels that each got.

#54 Add interface to module and sync output
  main.tf
  module.yaml
  outputs.tf
Labels: minor, feature

#55 Update bootstrap to v1.6.1
  main.tf
Labels: bug, patch

#56 Updates cloud-native-toolkit/terraform-tools-openshift-cicd module to v2.0.1
  README.md
  example/stage1-gitea.tf
  example/stage1-namespace.tf
  main.tf
  module.yaml
Labels: bug, minor
